interface=wlan0
driver=nl80211
ctrl_interface=/data/vendor/wifi/hostapd/ctrl_carlink
ssid=pi-carplay
country_code=US
ieee80211d=1
hw_mode=a
channel=36
ieee80211n=1
ieee80211ac=1
vht_oper_chwidth=0
wmm_enabled=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=12345678
